name: Bug Reporter

on:
  repository_dispatch:
    types: [create-bug-report]

jobs:
  create_github_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Decode Log Content and Prepare Gist Payload
        run: |
          # Decode the Base64 log content from the client payload
          DECODED_LOGS=$(echo "${{ github.event.client_payload.log_content_base64 }}" | base64 --decode)
          
          # Use jq to safely build the JSON payload with the decoded content
          jq -n \
            --arg desc "AMFormsCST Log File - $(date -u +"%Y-%m-%dT%H:%M:%SZ")" \
            --arg content "$DECODED_LOGS" \
            '{description: $desc, public: false, files: {"log.txt": {content: $content}}}' > gist_payload.json
        shell: bash

      - name: Create Gist for Logs
        id: create_gist
        run: |
          # Use curl to post the content of the file.
          GIST_RESPONSE=$(curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GH_PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/gists \
            --data-binary "@gist_payload.json")

          GIST_URL=$(echo "$GIST_RESPONSE" | jq -r .html_url)
          echo "GIST_URL=$GIST_URL" >> $GITHUB_OUTPUT
        shell: bash

      - name: Prepare Issue Body
        id: prepare_body
        run: |
          # Write the complete, multi-line issue body to a file.
          cat > issue_body.md <<EOF
          ${{ github.event.client_payload.description }}

          ---
          ### Environment
          - **App Version**: ${{ github.event.client_payload.app_version }}
          - **OS Version**: ${{ github.event.client_payload.os_version }}

          **Logs:** [View Logs on GitHub Gist](${{ steps.create_gist.outputs.GIST_URL }})
          EOF
        shell: bash

      - name: Create GitHub Issue
        uses: peter-evans/create-issue-from-file@v5
        with:
          token: ${{ secrets.GH_PAT }}
          title: ${{ github.event.client_payload.title }}
          content-filepath: ./issue_body.md
          labels: bug, reported-from-app
