name: Bug Reporter

# This action is triggered by a repository_dispatch event
on:
  repository_dispatch:
    types: [create-bug-report]

jobs:
  create_github_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Create Gist for Logs
        id: create_gist
        env:
          LOG_CONTENT: ${{ github.event.client_payload.log_content }}
        run: |
          # Use jq to safely build the JSON payload, preventing issues with special characters.
          JSON_PAYLOAD=$(jq -n \
            --arg desc "AMFormsCST Log File - $(date -u +"%Y-%m-%dT%H:%M-%SZ")" \
            --arg content "$LOG_CONTENT" \
            '{description: $desc, public: false, files: {"log.txt": {content: $content}}}')

          GIST_RESPONSE=$(curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GH_PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/gists \
            -d "$JSON_PAYLOAD")

          GIST_URL=$(echo "$GIST_RESPONSE" | jq -r .html_url)
          echo "GIST_URL=$GIST_URL" >> $GITHUB_OUTPUT
        shell: bash

      - name: Create Issue Body
        id: create_body
        run: |
          # Using a 'here document' to safely handle multi-line content
          mapfile -t BODY <<EOF
          ${{ github.event.client_payload.description }}

          ---
          ### Environment
          - **App Version**: ${{ github.event.client_payload.app_version }}
          - **OS Version**: ${{ github.event.client_payload.os_version }}

          **Logs:** [View Logs on GitHub Gist](${{ steps.create_gist.outputs.GIST_URL }})
          EOF
          
          # The peter-evans action needs the body in an environment variable
          echo "BODY<<EOF" >> $GITHUB_ENV
          printf '%s\n' "${BODY[@]}" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
        shell: bash

      - name: Create GitHub Issue
        uses: peter-evans/create-issue-from-file@v5
        with:
          token: ${{ secrets.GH_PAT }}
          title: ${{ github.event.client_payload.title }}
          body: ${{ env.BODY }}
          labels: bug, reported-from-app
