name: Bug Reporter

on:
  repository_dispatch:
    types: [create-bug-report]

jobs:
  create_github_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare Issue Body
        id: prepare_body
        run: |
          # Decode the description from Base64
          DECODED_DESCRIPTION=$(echo "${{ github.event.client_payload.description_base64 }}" | base64 --decode)

          # Write the complete, multi-line issue body to a file
          cat > issue_body.md <<EOF
          $DECODED_DESCRIPTION

          ---
          ### Environment
          - **App Version**: ${{ github.event.client_payload.app_version }}
          - **OS Version**: ${{ github.event.client_payload.os_version }}

          **Logs:** [View Logs on GitHub Gist](${{ github.event.client_payload.gist_url }})
          EOF
        shell: bash

      - name: Create GitHub Issue
        uses: peter-evans/create-issue-from-file@v5
        with:
          token: ${{ secrets.GH_PAT }}
          title: ${{ github.event.client_payload.title }}
          content-filepath: ./issue_body.md
          labels: bug, reported-from-app
