name: .NET Desktop Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    # This line is crucial: It ensures the job runs on a Windows machine.
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # Install the .NET 9 SDK
    - name: Setup .NET 9
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    # Restore dependencies
    - name: Restore
      run: dotnet restore

    # Build
    - name: Build
      run: dotnet build --no-restore --configuration Release

    # Test
    - name: Test
      run: dotnet test --no-build --configuration Release
